In [1]:
import pandas as pd

train_df = pd.read_csv('../../input/feedback-prize-2021/train.csv')
train_df.shape

(144293, 8)

In [2]:
train_df.head()

id  discourse_id  discourse_start  discourse_end  \
0  423A1CA112E2  1.622628e+12              8.0          229.0   
1  423A1CA112E2  1.622628e+12            230.0          312.0   
2  423A1CA112E2  1.622628e+12            313.0          401.0   
3  423A1CA112E2  1.622628e+12            402.0          758.0   
4  423A1CA112E2  1.622628e+12            759.0          886.0   

                                      discourse_text discourse_type  \
0  Modern humans today are always on their phone....           Lead   
1  They are some really bad consequences when stu...       Position   
2  Some certain areas in the United States ban ph...       Evidence   
3  When people have phones, they know about certa...       Evidence   
4  Driving is one of the way how to get around. P...          Claim   

  discourse_type_num                                   predictionstring  
0             Lead 1  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...  
1         Position 1       45 46 47 48 49 50 51 52 53 54 55 56 57 58 59  
2         Evidence 1    60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75  
3         Evidence 2  76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 9...  
4            Claim 1  139 140 141 142 143 144 145 146 147 148 149 15...

In [6]:
pd.read_csv('../../00_EDA/00_v2_04/result/unlabeled.csv')

essay_id  discourse_id  discourse_start  discourse_end  \
0       A8445CABFECE  1.622576e+12             18.0           85.0   
1       A8445CABFECE  1.622576e+12             86.0          202.0   
2       A8445CABFECE  1.622576e+12            203.0         1030.0   
3       A8445CABFECE  1.622576e+12           1031.0         1243.0   
4       6B4F7A0165B9  1.622644e+12             36.0          512.0   
...              ...           ...              ...            ...   
107523  AFEC37C2D43F  1.617803e+12           2029.0         2123.0   
107524  AFEC37C2D43F  1.617803e+12           2123.0         2702.0   
107525  AFEC37C2D43F  1.617803e+12           2703.0         2799.0   
107526  AFEC37C2D43F  1.617803e+12           2817.0         2907.0   
107527  AFEC37C2D43F  1.617803e+12           2907.0         3140.0   

                                           discourse_text  \
0       Drivers should not be able to use phones while...   
1       Drivers who used their phone while operating a...   
2       According to an article by the Edgar Snyder Fi...   
3       In conclusion, drivers should not able to work...   
4       The ability to stay connected to people we kno...   
...                                                   ...   
107523   misdeeds are when the advice-giver is purpose...   
107524  An example of this is when you ask Generic_Nam...   
107525  Now, I know what you probably saying "But what...   
107526   what are the odds that seven of your close fr...   
107527  The odds are in your favor; and the on the off...   

              discourse_type      discourse_type_num  \
0                   Position              Position 1   
1                      Claim                 Claim 1   
2                   Evidence              Evidence 1   
3       Concluding Statement  Concluding Statement 1   
4                       Lead                  Lead 1   
...                      ...                     ...   
107523                 Claim                 Claim 6   
107524              Evidence              Evidence 3   
107525          Counterclaim          Counterclaim 1   
107526              Rebuttal              Rebuttal 1   
107527  Concluding Statement  Concluding Statement 1   

                                         predictionstring  \
0                            3 4 5 6 7 8 9 10 11 12 13 14   
1       15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 3...   
2       36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 5...   
3       177 178 179 180 181 182 183 184 185 186 187 18...   
4       5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 ...   
...                                                   ...   
107523  354 355 356 357 358 359 360 361 362 363 364 36...   
107524  368 369 370 371 372 373 374 375 376 377 378 37...   
107525  465 466 467 468 469 470 471 472 473 474 475 47...   
107526  487 488 489 490 491 492 493 494 495 496 497 49...   
107527  505 506 507 508 509 510 511 512 513 514 515 51...   

                                            neighbor_text  
0       [POSITION]Drivers should not be able to use ph...  
1       [POSITION]Drivers should not be able to use ph...  
2       [POSITION]Drivers should not be able to use ph...  
3       [POSITION]Drivers should not be able to use ph...  
4       [LEAD]The ability to stay connected to people ...  
...                                                   ...  
107523  [CLAIM]The more similar iterations people give...  
107524  [EVIDENCE]Misunderstandings are harder to avoi...  
107525  [CLAIM]The best thing to do in a situation lik...  
107526  [CLAIM] misdeeds are when the advice-giver is ...  
107527  [EVIDENCE]An example of this is when you ask G...  

[107528 rows x 9 columns]

In [8]:
samples = list(train_df.groupby('id'))

In [10]:
text_id, df = samples[0]

In [11]:
text_id

'0000D23A521A'

In [12]:
df

id  discourse_id  discourse_start  discourse_end  \
59951  0000D23A521A  1.617735e+12              0.0          170.0   
59952  0000D23A521A  1.617735e+12            170.0          357.0   
59953  0000D23A521A  1.617735e+12            358.0          438.0   
59954  0000D23A521A  1.617735e+12            438.0          626.0   
59955  0000D23A521A  1.617735e+12            627.0          722.0   
59956  0000D23A521A  1.617735e+12            722.0          836.0   
59957  0000D23A521A  1.617735e+12            836.0         1014.0   
59958  0000D23A521A  1.617735e+12           1015.0         1343.0   

                                          discourse_text  \
59951  Some people belive that the so called "face" o...   
59952  It was not created by aliens, and there is no ...   
59953  A mesa is a naturally occuring rock formation,...   
59954  This "face" on mars only looks like a face bec...   
59955  Many conspiracy theorists believe that NASA is...   
59956  These people would be very wrong. If NASA foun...   
59957  NASA's budget would increase drasticly, which ...   
59958  So, NASA is not hiding life on Mars from us, a...   

             discourse_type      discourse_type_num  \
59951              Position              Position 1   
59952              Evidence              Evidence 1   
59953              Evidence              Evidence 2   
59954                 Claim                 Claim 1   
59955          Counterclaim          Counterclaim 1   
59956              Rebuttal              Rebuttal 1   
59957              Evidence              Evidence 3   
59958  Concluding Statement  Concluding Statement 1   

                                        predictionstring  
59951  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...  
59952  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 4...  
59953       69 70 71 72 73 74 75 76 77 78 79 80 81 82 83  
59954  84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 9...  
59955  117 118 119 120 121 122 123 124 125 126 127 12...  
59956  134 135 136 137 138 139 140 141 142 143 144 14...  
59957  154 155 156 157 158 159 160 161 162 163 164 16...  
59958  186 187 188 189 190 191 192 193 194 195 196 19...

In [13]:
from os.path import join as opj

text_path = opj('../../input/feedback-prize-2021/train/', f'{text_id}.txt')
with open(text_path) as f:
    text = f.read().rstrip()

In [50]:
text

'Some people belive that the so called "face" on mars was created by life on mars. This is not the case. The face on Mars is a naturally occuring land form called a mesa. It was not created by aliens, and there is no consiracy to hide alien lifeforms on mars. There is no evidence that NASA has found that even suggests that this face was created by aliens.\n\nA mesa is a naturally occuring rock formation, that is found on Mars and Earth. This "face" on mars only looks like a face because humans tend to see faces wherever we look, humans are obviously extremely social, which is why our brain is designed to recognize faces.\n\nMany conspiracy theorists believe that NASA is hiding life on Mars from the rest of the world. These people would be very wrong. If NASA found life on Mars, then they would get millions of people\'s attention. NASA\'s budget would increase drasticly, which means that their workers would get paid more. There is no good reason that NASA would hide life on Mars from th

In [2]:
from transformers import AutoTokenizer

model_name = 'roberta-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)

text = 'Hello, I am Tom.'

tokens = tokenizer(text, return_offsets_mapping=True)
offset_mapping = tokens['offset_mapping']

In [4]:
tokenizer.convert_ids_to_tokens(tokens['input_ids'])

['<s>', 'Hello', ',', 'ĠI', 'Ġam', 'ĠTom', '.', '</s>']

In [54]:
import re
import numpy as np

def strip_offset_mapping(text, offset_mapping):
    ret = []
    for start, end in offset_mapping:
        match = list(re.finditer('\S+', text[start:end]))
        if len(match) == 0:
            ret.append((start, end))
        else:
            span_start, span_end = match[0].span()
            ret.append((start + span_start, start + span_end))
    return np.array(ret)


def get_word_offsets(text):
    matches = re.finditer("\S+", text)
    spans = []
    words = []
    for match in matches:
        span = match.span()
        word = match.group()
        spans.append(span)
        words.append(word)
    assert tuple(words) == tuple(text.split())
    return np.array(spans)

In [56]:
# token slices of words (offset_mapping = character slices of tokens)

import torch

if True:
    if True:
        offset_mapping = np.array(tokens['offset_mapping'])
        offset_mapping = strip_offset_mapping(text, offset_mapping)
        
        woff = get_word_offsets(text) # (num_words,2) : character slices of words
        toff = offset_mapping # (num_tokens,2) : character slices of tokens
        wx1, wx2 = woff.T # (num_words,) x 2
        tx1, tx2 = toff.T # (num_tokens,) x 2
        ix1 = np.maximum(wx1[..., None], tx1[None, ...]) # (num_words,num_tokens)
        ix2 = np.minimum(wx2[..., None], tx2[None, ...]) # (num_words,num_tokens)
        ux1 = np.minimum(wx1[..., None], tx1[None, ...]) # (num_words,num_tokens)
        ux2 = np.maximum(wx2[..., None], tx2[None, ...]) # (num_words,num_tokens)
        ious = (ix2 - ix1).clip(min=0) / (ux2 - ux1 + 1e-12) # (num_words,num_tokens)
        assert (ious > 0).any(-1).all()
        
        word_boxes = []
        for row in ious: # ious.shape=(num_words,num_tokens)
            inds = row.nonzero()[0]
            word_boxes.append([inds[0], 0, inds[-1] + 1, 1])
        word_boxes = torch.FloatTensor(word_boxes)

In [97]:
LABEL2TYPE = ('Lead', 'Position', 'Claim', 'Counterclaim', 'Rebuttal',
              'Evidence', 'Concluding Statement')

TYPE2LABEL = {t: l for l, t in enumerate(LABEL2TYPE)}

# word slices of ground truth spans
if True:
    if True:
        gt_spans = []
        for _, row in df.iterrows():
            winds = row['predictionstring'].split()
            start = int(winds[0])
            end = int(winds[-1])
            span_label = TYPE2LABEL[row['discourse_type']]
            gt_spans.append([start, end + 1, span_label])
        gt_spans = torch.LongTensor(gt_spans)

In [118]:
text = "Hello, I'm Tom."
#       012345678901234

tokens = tokenizer(text, add_special_tokens=False, return_offsets_mapping=True)
offset_mapping = tokens['offset_mapping']
    
woff = get_word_offsets(text)
toff = offset_mapping

In [119]:
tokenizer.convert_ids_to_tokens(tokens['input_ids'])

['Hello', ',', 'ĠI', "'m", 'ĠTom', '.']

In [116]:
woff # [Hello(0,6), I'm(7,10), Tom.(11,15)]

array([[ 0,  6],
       [ 7, 10],
       [11, 15]])

In [117]:
toff # [Hello(0,5), ,(5,6), GI(7,8), 'm(8,10), GTom(11,14), .(14,15)]

[(0, 5), (5, 6), (7, 8), (8, 10), (11, 14), (14, 15)]

In [120]:
# token slices of words (offset_mapping = character slices of tokens)

import torch

if True:
    if True:
        offset_mapping = np.array(tokens['offset_mapping'])
        offset_mapping = strip_offset_mapping(text, offset_mapping)
        
        woff = get_word_offsets(text) # (num_words,2) : character slices of words
        toff = offset_mapping # (num_tokens,2) : character slices of tokens
        wx1, wx2 = woff.T # (num_words,) x 2
        tx1, tx2 = toff.T # (num_tokens,) x 2
        ix1 = np.maximum(wx1[..., None], tx1[None, ...]) # (num_words,num_tokens)
        ix2 = np.minimum(wx2[..., None], tx2[None, ...]) # (num_words,num_tokens)
        ux1 = np.minimum(wx1[..., None], tx1[None, ...]) # (num_words,num_tokens)
        ux2 = np.maximum(wx2[..., None], tx2[None, ...]) # (num_words,num_tokens)
        ious = (ix2 - ix1).clip(min=0) / (ux2 - ux1 + 1e-12) # (num_words,num_tokens)
        assert (ious > 0).any(-1).all()
        
        word_boxes = []
        for row in ious: # ious.shape=(num_words,num_tokens)
            inds = row.nonzero()[0]
            word_boxes.append([inds[0], 0, inds[-1] + 1, 1])
        word_boxes = torch.FloatTensor(word_boxes)

In [123]:
woff, toff

(array([[ 0,  6],
        [ 7, 10],
        [11, 15]]),
 array([[ 0,  5],
        [ 5,  6],
        [ 7,  8],
        [ 8, 10],
        [11, 14],
        [14, 15]]))

In [127]:
ix1

array([[ 0,  5,  7,  8, 11, 14],
       [ 7,  7,  7,  8, 11, 14],
       [11, 11, 11, 11, 11, 14]])

In [125]:
ix2

array([[ 5,  6,  6,  6,  6,  6],
       [ 5,  6,  8, 10, 10, 10],
       [ 5,  6,  8, 10, 14, 15]])

In [128]:
ux1

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  5,  7,  7,  7,  7],
       [ 0,  5,  7,  8, 11, 11]])

In [129]:
ux2

array([[ 6,  6,  8, 10, 14, 15],
       [10, 10, 10, 10, 14, 15],
       [15, 15, 15, 15, 15, 15]])

In [131]:
print(ious)

[[0.83333333 0.16666667 0.         0.         0.         0.        ]
 [0.         0.         0.33333333 0.66666667 0.         0.        ]
 [0.         0.         0.         0.         0.75       0.25      ]]


In [121]:
word_boxes

tensor([[0., 0., 2., 1.],
        [2., 0., 4., 1.],
        [4., 0., 6., 1.]])

In [134]:
import numpy as np
a = np.array([0,1,2,3])
' '.join(a.astype(str))

'0 1 2 3'